import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s);
const state={tab:'bones',bones:[],canals:[],passages:[],relationships:{},hierarchy:{},regions:[],boneParts:{},bonePartCatalog:[],model:null,selected:null,selectedEntry:null,exploded:false,isolated:false,treeFilter:'all',studyMode:null,studyTarget:null,viewed:JSON.parse(localStorage.getItem('atlasViewed')||'[]'),studyStats:JSON.parse(localStorage.getItem('atlasStudyStats')||'{"findCorrect":0,"findTotal":0,"quizCorrect":0,"quizTotal":0,"examRuns":0,"examBest":0}'),exam:null};
state.lab={active:false,part:null,labelEl:null};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071016);const camera=new THREE.PerspectiveCamera(42,1,.01,1000);camera.position.set(0,1,4.8);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;$('#scene').appendChild(renderer.domElement);
const labLabel=document.createElement('div');labLabel.className='lab-label';labLabel.style.display='none';$('#scene').appendChild(labLabel);state.lab.labelEl=labLabel;const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=.15;controls.maxDistance=20;scene.add(new THREE.HemisphereLight(0xe9f5ff,0x17222a,2.5));const l=new THREE.DirectionalLight(0xffffff,3);l.position.set(4,6,7);scene.add(l);const root3d=new THREE.Group();scene.add(root3d);const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();
function save(){localStorage.setItem('atlasStudyStats',JSON.stringify(state.studyStats));localStorage.setItem('atlasViewed',JSON.stringify(state.viewed))}function resize(){const r=$('#scene').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function frame(o){if(!o)return;const b=new THREE.Box3().setFromObject(o),c=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()),d=Math.max(s.x,s.y,s.z)/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2)));camera.position.copy(c).add(new THREE.Vector3(d*.1,d*.08,d*1.15));controls.target.copy(c);controls.update()}
function highlight(o){if(state.selected?.isMesh){state.selected.material?.emissive?.setHex(state.selected.userData.oldEmissive??0);state.selected.scale.copy(state.selected.userData.oldScale||new THREE.Vector3(1,1,1))}state.selected=o;if(o?.isMesh){if(o.material?.emissive){o.userData.oldEmissive=o.material.emissive.getHex();o.material.emissive.setHex(0x397a9e)}o.userData.oldScale=o.scale.clone();o.scale.multiplyScalar(1.018)}}
function norm(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[\s_.\-/:()[\]{}]+/g,'').replace(/^(left|right|l|r)[_ -]?/,'').replace(/[_-]?(left|right|l|r)$/,'')}function candidates(name){const n=norm(name);const part=state.bonePartCatalog.find(x=>x.modelNameCandidates?.some(c=>norm(c)===n)||norm(x.la)===n||norm(x.id)===n||n.includes(norm(x.la))||norm(x.la).includes(n));if(part)return part;return [...state.bones,...state.canals,...state.passages].find(x=>x.modelNameCandidates?.some(c=>norm(c)===n)||norm(x.la)===n||norm(x.id)===n||x.aliases?.some(c=>norm(c)===n)||x.modelNameCandidates?.some(c=>n.includes(norm(c))||norm(c).includes(n)))}function sideOf(x){const t=(x.la+' '+x.id+' '+(x.modelNameCandidates||[]).join(' ')).toLowerCase();if(/(^|[^a-z])(left|sin|sinistra|l)([^a-z]|$)/.test(t))return'L';if(/(^|[^a-z])(right|dex|dextra|r)([^a-z]|$)/.test(t))return'R';return'—'}function markViewed(x){if(!state.viewed.includes(x.la)){state.viewed.push(x.la);localStorage.setItem('atlasViewed',JSON.stringify(state.viewed))}}
function focusObject(o){const b=new THREE.Box3().setFromObject(o),c=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()),d=Math.max(s.x,s.y,s.z)/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2)));camera.position.copy(c).add(new THREE.Vector3(d*.15,d*.1,d*1.35));controls.target.copy(c);controls.update()}
function selectEntry(x){state.selectedEntry=x;if(x.parentId){renderPartCard(x);return}markViewed(x);if(state.studyMode==='find')return checkFindTarget(x);renderCard(x)}
function renderPartCard(x){const parent=getEntry(x.parentId);const linked=parent?`<p class="hint">Кость: <b>${parent.ru}</b> · ${parent.la}</p>`:'';$('#card').innerHTML=`<h2>${x.ru}</h2><div class="latin">${x.la}</div><p><b>Раздел:</b> ${x.group}</p>${linked}<div class="pill">Элемент кости</div><div class="actions"><button id="focusEntry">🎯 Найти на модели</button><button id="isolateEntry">◉ Изолировать</button><button id="parentEntry">↩ К кости</button><button id="showAll">↺ Показать всё</button></div><p class="hint">Если 3D-модель содержит отдельный mesh этого элемента, атлас сопоставит его автоматически. Иначе будет использована карточка элемента без выдуманного положения.</p>`;$('#focusEntry').onclick=()=>findEntryOnModel(x);$('#isolateEntry').onclick=()=>{const o=findMesh(x);if(o){highlight(o);isolate(o)}else toast('Отдельный mesh этого элемента пока не найден')};$('#parentEntry').onclick=()=>parent&&selectEntry(parent);$('#showAll').onclick=showAll}
function relationshipHtml(x){const r=state.relationships[x.id];if(!r)return '';let h='<section class=\"relations\"><h3>🔗 Анатомические связи</h3>';if(r.parts?.length)h+=`<p><b>Части:</b> ${r.parts.join(', ')}</p>`;if(r.landmarks?.length)h+=`<p><b>Ориентиры:</b> ${r.landmarks.join(', ')}</p>`;if(r.relations?.length)h+=`<p><b>Связано с:</b> ${r.relations.map(v=>`<span class=\"rel-chip\">${v}</span>`).join(' ')}</p>`;if(r.forms?.length)h+=`<p><b>Образует / относится к:</b> ${r.forms.join(', ')}</p>`;return h+'</section>'}\nfunction partsHtml(x){const p=state.boneParts?.[x.id];if(!p)return '';let h='<section class="bone-parts"><h3>🦴 Строение кости</h3><div class="parts-grid">';for(const g of p.groups||[]){h+=`<div class="part-group"><h4>${g.name}</h4><div class="part-list">`;for(const v of g.items){const m=v.match(/(.+?)\s+[—-]\s+(.+)$/);if(m){const la=m[2].trim();const part=state.bonePartCatalog.find(q=>q.parentId===x.id&&norm(q.la)===norm(la));h+=part?`<button class="part-button" data-part="${part.id}"><b>${m[1]}</b><small>${la}</small></button>`:`<div class="part-static">${v}</div>`}else h+=`<div class="part-static">${v}</div>`}h+='</div></div>'}h+='</div></section>';setTimeout(()=>document.querySelectorAll('.part-button').forEach(b=>b.onclick=()=>{const part=state.bonePartCatalog.find(q=>q.id===b.dataset.part);if(part)selectEntry(part)}),0);return h}\nfunction renderCard(x){if(state.tab==='bones')$('#card').innerHTML=`<h2>${x.ru}</h2><div class="latin">${x.la} · ${x.type}</div><p>${x.description}</p>${partsHtml(x)}${relationshipHtml(x)}<div class="pill">ID: ${x.id}</div><div class="pill">Сторона: ${sideOf(x)}</div><div class="actions"><button id="focusEntry">🎯 Найти на модели</button><button id="isolateEntry">◉ Изолировать</button><button id="showAll">↺ Показать всё</button></div><p class="hint">Mesh → анатомическая запись. Нажмите на структуру прямо в 3D или используйте поиск.</p>`;else $('#card').innerHTML=`<h2>${x.ru}</h2><div class="latin">${x.la}</div><p><b>Вход:</b> ${x.entrance}</p><p><b>Выход:</b> ${x.exit}</p><p><b>Содержимое:</b> ${x.contents}</p>${relationshipHtml(x)}<div class="pill">ID: ${x.id}</div><div class="actions"><button id="focusEntry">🎯 Найти на модели</button><button id="showAll">↺ Показать всё</button></div>`;$('#focusEntry')?.addEventListener('click',()=>findEntryOnModel(x));$('#isolateEntry')?.addEventListener('click',()=>{const o=findMesh(x);if(o){highlight(o);isolate(o)}else toast('Mesh структуры пока не найден в загруженной модели')});$('#showAll').onclick=showAll}
function findMesh(x){if(!state.model)return null;let found=null;state.model.traverse(o=>{if(found||!o.isMesh)return;const n=o.userData.sourceName||o.name;if(x.modelNameCandidates?.some(c=>norm(c)===norm(n))||norm(n)===norm(x.la)||norm(n)===norm(x.id))found=o});return found}function findEntryOnModel(x){const o=findMesh(x);if(!o){toast('Mesh структуры пока не найден в загруженной модели');return}highlight(o);focusObject(o);toast(`Фокус: ${x.ru}`)}function isolate(o){if(!state.model||!o)return;state.isolated=true;const key=o.userData.sourceName;state.model.traverse(m=>{if(m.isMesh)m.visible=(m===o||m.userData.sourceName===key)});highlight(o);focusObject(o);toast('Режим изоляции включён')}function showAll(){state.model?.traverse(m=>{if(m.isMesh)m.visible=true});state.isolated=false;toast('Показаны все структуры')}
const modelSources=['https://raw.githubusercontent.com/DrMuratAltun/anatomi-simulatoru/main/systems/skeleton.glb','https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/ScatteringSkull/glTF-Binary/ScatteringSkull.glb'];function loadModel(i=0){$('#modelStatus').textContent='3D engine: загрузка модели…';new GLTFLoader().load(modelSources[i],g=>{state.model=g.scene;state.model.traverse(o=>{if(o.isMesh)o.userData.sourceName=o.name});root3d.add(state.model);frame(state.model);$('#modelStatus').textContent=i===0?'3D engine: separated skeleton GLB ✓':'3D engine: fallback skull GLB ✓'},undefined,()=>i+1<modelSources.length?loadModel(i+1):$('#modelStatus').textContent='3D engine: модель недоступна — база и интерфейс работают')}loadModel();
renderer.domElement.addEventListener('click',e=>{if(!state.model)return;const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(state.model,true)[0];if(!hit)return;highlight(hit.object);const name=hit.object.userData.sourceName||hit.object.name||'Mesh';if(state.studyMode==='find'){checkFindMesh(name,hit.object);return}const entry=candidates(name);entry?selectEntry(entry):showModelSelection(name)});
function showModelSelection(name){$('#card').innerHTML=`<h2>Выбранный 3D-объект</h2><div class="latin">${name}</div><p>Mesh выбран непосредственно в 3D. Для этого имени пока нет точного сопоставления в анатомической базе.</p><div class="actions"><button id="focusSel">🎯 Фокус</button><button id="isolateSel">◉ Изолировать</button></div>`;$('#focusSel').onclick=()=>state.selected&&focusObject(state.selected);$('#isolateSel').onclick=()=>isolate(state.selected)}
async function loadData(){state.bones=await(await fetch('./data/bones.json')).json();state.canals=await(await fetch('./data/canals.json')).json();state.passages=await(await fetch('./data/passages.json')).json();state.relationships=await(await fetch('./data/relationships.json')).json();state.hierarchy=await(await fetch('./data/hierarchy.json')).json();state.regions=await(await fetch('./data/regions.json')).json();state.boneParts=await(await fetch('./data/bone_parts.json')).json();state.bonePartCatalog=await(await fetch('./data/bone_part_catalog.json')).json();renderList()}function renderList(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));const q=$('#search').value.toLowerCase(),source=state.tab==='passages'?state.passages:state[state.tab],arr=source.filter(x=>{const m=(x.ru+' '+x.la+' '+JSON.stringify(x)).toLowerCase().includes(q);return state.tab!=='bones'||state.treeFilter==='all'?m:state.treeFilter==='paired'?m&&x.typeKey==='paired':m&&x.typeKey==='unpaired'});$('#list').innerHTML=arr.map((x,i)=>`<button class="item" data-i="${i}"><b>${x.ru}</b><small>${x.la}</small></button>`).join('');document.querySelectorAll('.item').forEach(b=>b.onclick=()=>selectEntry(arr[+b.dataset.i]))}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.treeFilter='all';renderList()});$('#search').oninput=renderList;$('#treeAll').onclick=()=>{state.treeFilter='all';renderList()};$('#treePaired').onclick=()=>{state.treeFilter='paired';state.tab='bones';renderList()};$('#treeUnpaired').onclick=()=>{state.treeFilter='unpaired';state.tab='bones';renderList()};$('#mappingBtn').onclick=showMapping;$('#resetProgress').onclick=resetProgress;$('#reset').onclick=()=>state.model&&frame(state.model);$('#explode').onclick=()=>{state.exploded=!state.exploded;if(state.model)state.model.position.x=state.exploded?.35:0;toast(state.exploded?'Режим разборки включён':'Модель собрана')};$('#boneLayer').onchange=e=>root3d.visible=e.target.checked;$('#labels').onchange=e=>toast(e.target.checked?'Подписи включены':'Подписи скрыты');
function updateStudyPanel(){const p=$('#studyPanel');if(!state.studyMode){p.style.display='none';return}p.style.display='block';if(state.studyMode==='learn')p.innerHTML=`<h2>📚 Режим изучения</h2><p>Выбирай структуру в списке или кликай по 3D. После открытия карточки используй <b>Найти на модели</b> и <b>Изолировать</b>.</p><div class="study-stat">Изучено: <b>${state.viewed.length}</b> структур</div><button id="exitStudy">Завершить режим</button>`;else{const t=state.studyTarget;p.innerHTML=`<h2>🎯 Найди структуру</h2><p>Найди на 3D-модели: <strong>${t.ru}</strong></p><div class="latin">${t.la}</div><p class="hint">Кликни по предполагаемой структуре. Ответ будет проверен автоматически.</p><button id="newFind">Новая цель</button><button id="exitStudy">Завершить режим</button>`}$('#exitStudy').onclick=exitStudy;$('#newFind')?.addEventListener('click',startFind)}function startLearn(){state.studyMode='learn';state.studyTarget=null;showAll();updateStudyPanel();toast('Режим изучения включён')}function startFind(){if(!state.bones.length)return;state.studyMode='find';state.studyTarget=[...state.bones,...state.canals,...state.passages].filter(x=>x.modelNameCandidates?.length)[Math.floor(Math.random()*[...state.bones,...state.canals,...state.passages].filter(x=>x.modelNameCandidates?.length).length)];showAll();updateStudyPanel();toast('Найди структуру непосредственно на модели')}function exitStudy(){state.studyMode=null;state.studyTarget=null;updateStudyPanel();$('#card').innerHTML='<h2>3D Anatomy Atlas</h2><p>Выбери структуру в базе или непосредственно на 3D-модели.</p>'}function checkFindMesh(name,obj){if(!state.studyTarget){startFind();return}state.studyStats.findTotal++;const entry=candidates(name);if(entry&&entry.la===state.studyTarget.la){state.studyStats.findCorrect++;save();highlight(obj);focusObject(obj);toast('✓ Верно!');setTimeout(startFind,700)}else{save();toast(`✗ Это не ${state.studyTarget.ru}`)}}function checkFindTarget(x){const o=findMesh(x);o?(highlight(o),focusObject(o),toast('Цель найдена в базе — теперь кликни по ней в 3D')):toast('Эта структура пока не сопоставлена с mesh модели')}
$('#studyBtn').onclick=startLearn;$('#findBtn').onclick=startFind;$('#progressBtn').onclick=()=>open(`<h2>📊 Прогресс</h2><p>Просмотрено структур: <b>${state.viewed.length}</b> из ${state.bones.length+state.canals.length+state.passages.length}.</p><p>«Найди»: <b>${state.studyStats.findCorrect}</b> верных из <b>${state.studyStats.findTotal}</b>.</p><p>Тест: <b>${state.studyStats.quizCorrect}</b> верных из <b>${state.studyStats.quizTotal}</b>.</p><p>Экзаменов: <b>${state.studyStats.examRuns}</b>. Лучший результат: <b>${state.studyStats.examBest}</b> правильных ответов.</p><p class="hint">Прогресс хранится только в localStorage этого браузера.</p>`);$('#aboutBtn').onclick=()=>open(`<h2>3D Anatomy Atlas — Beta 1.11</h2><p>Независимый учебный атлас: 3D-вьюер, анатомическая база и учебные режимы разделены.</p><ul><li>Изучение: карточка → фокус → изоляция.</li><li>Найди структуру: цель выбирается автоматически, ответ проверяется кликом по 3D.</li><li>Мини-тест и локальная статистика.</li><li>Экзамен: 5/10/15 вопросов, таймер, результат и лучший результат.</li><li>База расширена: кости, каналы и отверстия/щели с входом, выходом и содержимым.</li></ul><p class="hint">Проект не является клиническим приложением.</p>`);$('#quizBtn').onclick=async()=>{const qs=await(await fetch('./data/questions.json')).json(),q=qs[Math.floor(Math.random()*qs.length)];open(`<h2>🧠 Мини-тест</h2><p><b>${q.q}</b></p>${q.options.map((x,i)=>`<button class="q" data-a="${i}">${String.fromCharCode(65+i)} — ${x}</button>`).join('')}`);document.querySelectorAll('.q').forEach(b=>b.onclick=()=>{state.studyStats.quizTotal++;if(+b.dataset.a===q.answer)state.studyStats.quizCorrect++;save();close();toast(+b.dataset.a===q.answer?'✓ Верно!':'✗ Правильный ответ: '+String.fromCharCode(65+q.answer))})};
function examSetup(){open(`<h2>🏆 Экзамен</h2><p>Серия вопросов с таймером. Результат сохраняется локально.</p><div class="exam-grid"><label>Вопросов<select id="examCount"><option value="5">5</option><option value="10" selected>10</option><option value="15">15</option></select></label><label>Время<select id="examTime"><option value="120">2 минуты</option><option value="300" selected>5 минут</option><option value="600">10 минут</option></select></label></div><button id="startExam">▶ Начать экзамен</button>`);$('#startExam').onclick=()=>startExam(+$('#examCount').value,+$('#examTime').value)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
async function startExam(count,seconds){const qs=await(await fetch('./data/questions.json')).json();let pool=shuffle(qs);while(pool.length<count)pool=pool.concat(shuffle(qs));pool=pool.slice(0,count).map(q=>({...q,options:shuffle(q.options.map((text,i)=>({text,correct:i===q.answer}))),answer:0}));pool.forEach(q=>q.answer=q.options.findIndex(x=>x.correct));state.exam={pool,index:0,correct:0,answers:[],secondsLeft:seconds,totalSeconds:seconds,timer:null};renderExam();state.exam.timer=setInterval(()=>{if(!state.exam)return;state.exam.secondsLeft--;renderExamTimer();if(state.exam.secondsLeft<=0)finishExam(true)},1000)}
function renderExamTimer(){const e=$('#examTimer');if(e)e.textContent=formatTime(state.exam.secondsLeft);const bar=$('#examBar');if(bar)bar.style.width=Math.max(0,state.exam.secondsLeft/state.exam.totalSeconds*100)+'%'}
function formatTime(n){n=Math.max(0,n);return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function renderExam(){if(!state.exam)return;const e=state.exam,q=e.pool[e.index],pct=e.index/e.pool.length*100;open(`<div class="exam-head"><div><b>🏆 Экзамен</b><div class="hint">Вопрос ${e.index+1} из ${e.pool.length}</div></div><div class="timer" id="examTimer">${formatTime(e.secondsLeft)}</div></div><div class="exam-progress"><i id="examBar" style="width:${e.secondsLeft/e.totalSeconds*100}%"></i></div><p><b>${q.q}</b></p>${q.options.map((x,i)=>`<button class="q" data-a="${i}">${String.fromCharCode(65+i)} — ${x.text}</button>`).join('')}<button id="finishExam">Завершить сейчас</button>`);document.querySelectorAll('.q').forEach(b=>b.onclick=()=>answerExam(+b.dataset.a));$('#finishExam').onclick=()=>finishExam(false)}
function answerExam(a){const e=state.exam;if(!e)return;const q=e.pool[e.index];e.answers[e.index]=a;if(a===q.answer)e.correct++;e.index++;if(e.index>=e.pool.length)finishExam(false);else renderExam()}
function finishExam(timeout){const e=state.exam;if(!e)return;clearInterval(e.timer);state.studyStats.examRuns++;state.studyStats.examBest=Math.max(state.studyStats.examBest,e.correct);save();const pct=Math.round(e.correct/e.pool.length*100);state.exam=null;open(`<h2>🏁 Результат экзамена</h2><div class="result-stat"><span class="pill">${e.correct} / ${e.pool.length}</span><span class="pill">${pct}%</span><span class="pill">${timeout?'Время вышло':'Завершён'}</span></div><p>${pct>=80?'Экзамен завершён.':'Экзамен завершён.'}</p><p class="hint">Лучший результат в этом браузере: ${state.studyStats.examBest} правильных ответов.</p><button id="againExam">Повторить</button>`);$('#againExam').onclick=examSetup}
$('#examBtn').onclick=examSetup;$('#labBtn').onclick=()=>{const x=state.selectedEntry?.parentId?state.selectedEntry:state.selectedEntry?.category==='bone'?state.selectedEntry:null;startLab(x)};$('#relationsBtn').onclick=showRelations;$('#treeBtn').onclick=buildAnatomyTree;$('#regionsBtn').onclick=showRegions;
function startLab(x){
  if(!x){open('<h2>🧪 Анатомическая лаборатория</h2><p>Выберите кость из списка, затем откройте её элементы. Лаборатория показывает выбранный элемент, пытается найти его mesh и может изолировать его.</p>');return}
  state.lab.active=true; state.lab.part=x;
  const parent=x.parentId?getEntry(x.parentId):x;
  const parts=parent?state.bonePartCatalog.filter(p=>p.parentId===parent.id):[];
  let html=`<h2>🧪 ${parent?.ru||x.ru}</h2><div class="latin">${parent?.la||x.la}</div><p class="hint">Лаборатория: выберите элемент, затем используйте фокус или изоляцию. Подпись появляется прямо поверх 3D-сцены.</p>`;
  if(parts.length){html+='<div class="lab-parts">';for(const p of parts){html+=`<button class="lab-part ${p.id===x.id?'active':''}" data-id="${p.id}"><b>${p.ru}</b><small>${p.la}</small></button>`}html+='</div>'}
  html+=`<div class="lab-actions"><button id="labFocus">🎯 Фокус</button><button id="labIsolate">◉ Изолировать</button><button id="labShow">↺ Показать всё</button><button id="labClose">Закрыть</button></div><div id="labInfo" class="lab-info"></div>`;
  open(html);
  document.querySelectorAll('.lab-part').forEach(b=>b.onclick=()=>{const p=state.bonePartCatalog.find(v=>v.id===b.dataset.id);if(p)startLab(p)});
  $('#labFocus').onclick=()=>labFocus(x);$('#labIsolate').onclick=()=>labIsolate(x);$('#labShow').onclick=showAll;$('#labClose').onclick=()=>{state.lab.active=false;labLabel.style.display='none';close()};
  updateLabInfo(x);
  labFocus(x);
}
function updateLabInfo(x){const el=$('#labInfo');if(!el)return;const o=findMesh(x);el.innerHTML=o?`<span class="lab-ok">✓ Mesh найден</span><p class="hint">Источник: ${o.userData.sourceName||o.name||'mesh'}</p>`:`<span class="lab-miss">○ Отдельный mesh не найден</span><p class="hint">Карточка доступна, но текущая GLB-модель не содержит подтверждённого отдельного объекта для этого элемента.</p>`}
function labFocus(x){const o=findMesh(x);if(!o){updateLabInfo(x);toast('Отдельный mesh элемента пока не найден');return}highlight(o);focusObject(o);showLabLabel(x,o);updateLabInfo(x)}
function labIsolate(x){const o=findMesh(x);if(!o){updateLabInfo(x);toast('Нельзя изолировать: mesh элемента не найден');return}highlight(o);isolate(o);showLabLabel(x,o);updateLabInfo(x)}
function showLabLabel(x,o){state.lab.part=x;labLabel.textContent=`${x.ru} · ${x.la}`;labLabel.style.display='block';labLabel.dataset.objectId=o.uuid}
function updateLabLabel(){if(!state.lab.active||!state.lab.part||labLabel.style.display==='none'||!state.model)return;let o=null;state.model.traverse(m=>{if(m.uuid===labLabel.dataset.objectId)o=m});if(!o)return;const b=new THREE.Box3().setFromObject(o),c=b.getCenter(new THREE.Vector3()),v=c.project(camera),r=$('#scene').getBoundingClientRect();if(v.z< -1 || v.z>1){labLabel.style.display='none';return}labLabel.style.display='block';labLabel.style.left=((v.x+1)/2*r.width)+'px';labLabel.style.top=((1-v.y)/2*r.height)+'px'}
function showMapping(){if(!state.model){open('<h2>🔗 Mapping</h2><p>3D-модель ещё не загружена.</p>');return}const all=[...state.bones,...state.canals,...state.passages];let meshes=[];state.model.traverse(o=>{if(o.isMesh)meshes.push(o)});const matched=all.filter(x=>findMesh(x)).length;const unmatched=all.length-matched;open(`<h2>🔗 Mapping 3D ↔ база</h2><div class="result-stat"><span class="pill">Записей: ${all.length}</span><span class="pill">Mesh: ${meshes.length}</span><span class="pill">Сопоставлено: ${matched}</span><span class="pill">Без сопоставления: ${unmatched}</span></div><p class="hint">Это техническая диагностика: совпадение определяется по именам mesh и modelNameCandidates. Наличие записи в базе не означает, что структура уже присутствует в текущем 3D-ассете.</p>`)}
function getEntry(id){return [...state.bones,...state.canals,...state.passages].find(x=>x.id===id)}
function nodeButton(x,depth=0){if(!x)return '';const kind=x.category==='bone'?'🦴':x.category==='canal'?'🕳️':'↔️';return `<button class="anatomy-node" style="--depth:${depth}" data-node-id="${x.id}"><span>${kind}</span><b>${x.ru}</b><small>${x.la}</small></button>`}
function buildAnatomyTree(){const h=state.hierarchy||{};let html='<h2>🌳 Анатомическое дерево</h2><p class="hint">Навигация идёт от отдела черепа или кости к конкретному каналу, отверстию или щели.</p><div class="anatomy-tree">';
for(const region of (h.skull_regions||[])){html+=`<details open><summary>🧠 ${region.ru}</summary>`;for(const id of region.children||[]){const x=getEntry(id);if(x)html+=nodeButton(x,1)}html+='</details>'}
html+='<details open><summary>🕳️ Каналы и проходы по кости</summary>';for(const group of h.pathways||[]){html+=`<details class="tree-group"><summary>${group.ru}</summary>`;for(const id of group.children||[]){const x=getEntry(id);if(x)html+=nodeButton(x,2)}html+='</details>'}html+='</details></div>';
open(html);document.querySelectorAll('.anatomy-node').forEach(b=>b.onclick=()=>{const x=getEntry(b.dataset.nodeId);if(!x)return;close();state.tab=x.category==='bone'?'bones':x.category==='canal'?'canals':'passages';state.treeFilter='all';renderList();selectEntry(x);const o=findMesh(x);if(o){highlight(o);focusObject(o)}})}

function showRegions(){let html='<h2>🦴 Скелет</h2><p class="hint">Отдел → кость → конкретная кость кисти, стопы или часть скелета. Сопоставление с 3D зависит от имён mesh текущего ассета.</p><div class="region-grid">';for(const r of state.regions){html+=`<section class="region-card"><h3>${r.ru}</h3><div>${r.children.map(id=>{const x=getEntry(id);return x?`<button class="region-bone" data-id="${id}">${x.ru}<small>${x.la}</small></button>`:''}).join('')}</div></section>`}html+='</div>';open(html);document.querySelectorAll('.region-bone').forEach(b=>b.onclick=()=>{const x=getEntry(b.dataset.id);close();state.tab='bones';state.treeFilter='all';renderList();selectEntry(x);const o=findMesh(x);if(o){highlight(o);focusObject(o)}})}
function showRelations(){const all=[...state.bones,...state.canals,...state.passages];const rows=all.filter(x=>state.relationships[x.id]).map(x=>{const r=state.relationships[x.id];return `<button class=\"relation-row\" data-id=\"${x.id}\"><b>${x.ru}</b><small>${x.la} · ${r.relations?.length||0} связей</small></button>`}).join('');open(`<h2>🧩 Карта связей</h2><p class=\"hint\">Выбери структуру, чтобы открыть её анатомические связи, части и ориентиры.</p><div class=\"relation-list\">${rows}</div>`);document.querySelectorAll('.relation-row').forEach(b=>b.onclick=()=>{const x=all.find(a=>a.id===b.dataset.id);close();state.tab=x.category==='bone'?'bones':x.category==='canal'?'canals':'passages';renderList();selectEntry(x)})}\nfunction resetProgress(){if(confirm('Сбросить локальный прогресс этого браузера?')){state.viewed=[];state.studyStats={findCorrect:0,findTotal:0,quizCorrect:0,quizTotal:0,examRuns:0,examBest:0};save();toast('Прогресс сброшен');}}
function open(h){$('#modalBox').innerHTML=h;$('#modal').style.display='flex'}function close(){$('#modal').style.display='none'}$('#modal').onclick=e=>{if(e.target.id==='modal'&&!state.exam)close()};function toast(t){const e=document.createElement('div');e.textContent=t;e.className='toast';document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}addEventListener('keydown',e=>{if(e.key==='Escape'&&!state.exam)close();if(e.key.toLowerCase()==='r'&&state.model)frame(state.model);if(e.key.toLowerCase()==='i'&&state.selected)isolate(state.selected);if(e.key.toLowerCase()==='a')showAll()});function animate(){requestAnimationFrame(animate);controls.update();updateLabLabel();renderer.render(scene,camera)}animate();loadData();
